### ISSUE TITLE
[Question] Lectern of other mods 

### ISSUE THREAD

**Issue by MbtMarco** [Bimbusick/lectern-overhaul#1]
First of all beautiful datapack, secondly I was wondering if the mods that spawning structures with a lectern already inside them work like the mod, or is it necessary for the player to put the book?

**Comment by Bimbusick** [comment]
1. thanks! 
2. it's necessary for the player to put the book, because to replace books from lecterns with updated ones, it will need to find the closest lecterns and make the necessary operations with them, which is not quite performant.

**Comment by MbtMarco** [comment]
Would you ever make an add-on for this in the future?

**Comment by Bimbusick** [comment]
yeah, i think
